### ISSUE TITLE
An insufficient number of arguments were supplied for the procedure or function cdc.fn_cdc_get_all_changes_ ... .

### ISSUE THREAD

**Issue by ashokgkumar** [jpalomo/kafka-connect-mssqlserver-cdc#2]
Hello John,

I am getting "An insufficient number of arguments were supplied for the procedure or function cdc.fn_cdc_get_all_changes_ ... ." error.  I can see that you have a condition to check for invalid/null LSN before querying the cdc changes function but in this case the LSN returned by TIME_TO_LSN is valid but the LSN does not exist in the capture  instance.  Would it make sense to set the min_lsn to 
select sys.fn_cdc_get_min_lsn('dbo_EMAIL') when the above call throws an error.

[2017-11-22 18:35:30,269] INFO Created connector mssql-cdc-source-connector (org.apache.kafka.connect.cli.ConnectStandalone:91)
[2017-11-22 18:35:30,371] TRACE created new timestamp from map: 2017-11-22 15:20:11.95 (com.github.jpalomo.connect.cdc.mssqlserver.TimestampOffset:64)
[2017-11-22 18:35:30,372] TRACE created new timestamp from map: 2017-11-22 15:20:11.95 (com.github.jpalomo.connect.cdc.mssqlserver.TimestampOffset:64)
[2017-11-22 18:35:30,372] INFO Querier added: CaptureInstanceQuerier{ databaseName='cdc_test', topic='dbo_EMAIL', lastquery='0', fetchSize='500', offset='2017-11-22 15:20:11.95', table='CdcTableConfig{ sourceSchema='dbo', sourceTable='EMAIL', captureInstance='dbo_EMAIL', objectId='1957582012', sourceObjectId='1525580473', startLsn='0000006F00004810004E', endLsn='null', supportsNetChanges='true', roleName='null', indexName='PK__EMAIL__B916E1C6C0F6554C', fileGroupName='null', createDate='2017-11-22 16:00:32.983', indexColumnList='EMAILID', capturedColumnList='EMAILID'FIRST_NAME'LAST_NAME'EMAILADDRESS'MODIFIED_DATE'DOMAIN_NAME' }'} (com.github.jpalomo.connect.cdc.mssqlserver.CdcSourceTask:100)
[2017-11-22 18:35:30,373] TRACE created new timestamp from map: 2017-11-16 15:31:50.447 (com.github.jpalomo.connect.cdc.mssqlserver.TimestampOffset:64)
[2017-11-22 18:35:30,373] TRACE created new timestamp from map: 2017-11-16 15:31:50.447 (com.github.jpalomo.connect.cdc.mssqlserver.TimestampOffset:64)
[2017-11-22 18:35:30,373] INFO Querier added: CaptureInstanceQuerier{ databaseName='cdc_test', topic='dbo_PERSON', lastquery='0', fetchSize='500', offset='2017-11-16 15:31:50.447', table='CdcTableConfig{ sourceSchema='dbo', sourceTable='PERSON', captureInstance='dbo_PERSON', objectId='965578478', sourceObjectId='917578307', startLsn='0000005F00007AD00001', endLsn='null', supportsNetChanges='true', roleName='null', indexName='PK__PERSON__AA2FFB85C4F4775A', fileGroupName='null', createDate='2017-11-06 22:31:34.417', indexColumnList='PersonID', capturedColumnList='PersonID'FIRST_NAME'LAST_NAME'MODIFIED_DATE' }'} (com.github.jpalomo.connect.cdc.mssqlserver.CdcSourceTask:100)
[2017-11-22 18:35:30,373] INFO Source task WorkerSourceTask{id=mssql-cdc-source-connector-0} finished initialization and start (org.apache.kafka.connect.runtime.WorkerSourceTask:143)
[2017-11-22 18:35:30,373] TRACE Nothing to send to Kafka. Polling source for additional records (org.apache.kafka.connect.runtime.WorkerSourceTask:162)
[2017-11-22 18:35:30,373] TRACE ENTER: poll (com.github.jpalomo.connect.cdc.mssqlserver.CdcSourceTask:109)
com.microsoft.sqlserver.jdbc.SQLServerException: An insufficient number of arguments were supplied for the procedure or function cdc.fn_cdc_get_all_changes_ ... .
	at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet$FetchBuffer.nextRow(SQLServerResultSet.java:6309)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.fetchBufferNext(SQLServerResultSet.java:1651)
	at com.microsoft.sqlserver.jdbc.SQLServerResultSet.next(SQLServerResultSet.java:987)
	at com.github.jpalomo.connect.cdc.mssqlserver.CaptureInstanceQuerier.next(CaptureInstanceQuerier.java:149)
	at com.github.jpalomo.connect.cdc.mssqlserver.CdcSourceTask.poll(CdcSourceTask.java:127)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:163)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:146)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:190)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2017-11-22 18:35:30,416] DEBUG Resetting querier CaptureInstanceQuerier{ databaseName='cdc_test', topic='dbo_EMAIL', lastquery='0', fetchSize='500', offset='2017-11-22 15:20:11.95', table='CdcTableConfig{ sourceSchema='dbo', sourceTable='EMAIL', captureInstance='dbo_EMAIL', objectId='1957582012', sourceObjectId='1525580473', startLsn='0000006F00004810004E', endLsn='null', supportsNetChanges='true', roleName='null', indexName='PK__EMAIL__B916E1C6C0F6554C', fileGroupName='null', createDate='2017-11-22 16:00:32.983', indexColumnList='EMAILID', capturedColumnList='EMAILID'FIRST_NAME'LAST_NAME'EMAILADDRESS'MODIFIED_DATE'DOMAIN_NAME' }'} (com.github.jpalomo.connect.cdc.mssqlserver.CdcSourceTask:158)
[2017-11-22 18:35:30,417] TRACE Nothing to send to Kafka. Polling source for additional records (org.apache.kafka.connect.runtime.WorkerSourceTask:162)

**Min LSN available in SQL for the capture instance**

select sys.fn_cdc_get_min_lsn('dbo_EMAIL')
--0x0000006F00004810004E

**TIME_TO_LSN - Resolved Value** which is throwing error.

select sys.fn_cdc_map_time_to_lsn('smallest greater than', CONVERT(datetime, '2017-11-22 15:20:11.95'))
--0x0000006E00007D800001

**Comment by jpalomo** [comment]
I don't think your suggestion about resetting the offset to the min LSN when this occurs is not a bad idea.  However, I am curious as to how you go to this state.  I spent a lot of time getting these queries working and fighting through these lame and ambiguous errors.  More often than not, it had to do with my test database.   I was either dropping/recreating the database disabling/enabling CDC.  The state offset information from the old database is persisted in Kafka.

Could this be the case for you?  The following line looks a little suspicious to me:
[**2017-11-22 18:35:30,416**] DEBUG Resetting querier CaptureInstanceQuerier{ databaseName='cdc_test', topic='dbo_EMAIL', lastquery='0', fetchSize='500', offset='**2017-11-22 15:20:11.95** table='CdcTableConfig{ ...

Just because the last persisted offset was 3 days before this error.  Was it possible you dropped, enabled, or performed some other CDC admin function in the past 3 days? I dont believe CDC purges LSNs (which would invalidate valid timestamps) but this could be an anomaly on MSSQL side.  

Let me know and I would be happy to try and reproduce this issue and put in a fix.  until then, I think I will keep the error.  (I probably should have exited if I got this error).  If this is something that should not happen, or perhaps indicates a deeper issue (corruption of cdc info), I might even have the connector exit.  Thanks again!

**Comment by ashokgkumar** [comment]
It happens anytime you disable a capture instance and enable a new instance using the same name - It is a valid case in MSSQL as you can recreate a new instance using an old name.  But I believe the stored offset for the recreated capture instance is way off resulting in the error above.

**Comment by jpalomo** [comment]
I see your point and I think it is valid.  I'm thinking this can be handled in a couple of different ways.  

1. Create a table monitor thread similar to how confluent monitors database metadata.  [Table Monitor Thread](https://github.com/confluentinc/kafka-connect-jdbc/blob/master/src/main/java/io/confluent/connect/jdbc/JdbcSourceConnector.java#L123).   If a capture instance is dropped from the database, delete/reset the offsets for this table.

2. Handle this in a way similar to how the stream applications.  When a capture instance is going to be dropped, remove the white-listed capture instance table & reset the configs using a tool like the stream application reset tool.  

I totally get that this is a valid scenario in SQL Server but I think the first scenario might complicate things.  And I am not sure how often this type of scenario would happen in an enterprise environment and am hesitant to add code for something that doesn't happen often (outside of a dev environment).

I am in favor of option 2 because if we were to use the Confluent Control center, you shouldn't even be able to create the connector with that table configured if it didn't exist (i.e. it wouldn't be a valid configuration).  If a white-listed capture instance gets dropped during run-time, I would think this would cause a connector to fail as the explicit white-listed table no longer exists.

What do you think?

**Comment by ashokgkumar** [comment]
I do think that we may still need a table monitor thread cause metadata changes in sql cdc does not get applied automatically.  To overcome the problem and without losing old captured data, the suggested solution is to create a new capture instance for the source table in order to reflect the table structure change, copy the captured data from the old capture instance to the new created one, and then disable the old capture instance. This being a very common scenario must be handled well.  The table thread monitor can help identify new capture instance and request a task reconfiguration to whitelist the new capture instance and may be drop the old one.  

For a dropped capture instance, it makes sense to reset the config using the tool.

**Comment by ashokgkumar** [comment]
Another thought on the insufficient number of arguments error - we could directly query the cdc table instead of the sql function.  Querying the table always yields proper results and the scenario would never arise.  May be a workable solution till MS provides a proper fix to the issue.

	private static final String CDC_PARAMERTEIZED_QUERY = "SELECT sys.fn_cdc_map_lsn_to_time(__$start_lsn) as "
			+ LSN_TIMESTAMP_LABEL + ", * FROM cdc.%s_CT t with (nolock)	where (t.__$operation = 1 or t.__$operation = 2 or t.__$operation = 4 or "
			+ "t.__$operation = 3 ) and (t.__$start_lsn <= sys.fn_cdc_get_max_lsn()) "
			+ "and (t.__$start_lsn >= "+TIME_TO_LSN+")";

**Comment by jpalomo** [comment]
@ashokgkumar I actually entertained this approach when initially developing this.  It seemed to work just fine and would definitely help with the situation you are having.  However, I did find that Microsoft strongly recommends not querying the system tables directly.  I am not a database expert by any means and couldn't quite understand their rationale for this, but I went with their recommendation.

https://docs.microsoft.com/en-us/sql/relational-databases/system-tables/cdc-capture-instance-ct-transact-sql

From the above link:
> We recommend that you **do not query the system tables directly**. Instead, execute the cdc.fn_cdc_get_all_changes_<capture_instance> and cdc.fn_cdc_get_net_changes_<capture_instance> functions.

**Comment by ashokgkumar** [comment]
Yes, I understand, it's bad, un-recommended by Microsoft, reinventing the wheel. But it works and I don't get weird functions messing up the flow with obscure error messages.  The error is not even related to the actual table being queried.  The thing I really hate about it is that it puts the task in a unrecoverable situation unless the offset store is wiped out.  We could may be have a switch in the configuration that will help us recover from the above error using the direct query option in case we ever run into this situation.

**Comment by jpalomo** [comment]
@ashokgkumar sorry it took a while to get back to you.  I did a little research and I think the change you are proposing is reasonable.  Check it out [here](https://github.com/jpalomo/kafka-connect-mssqlserver-cdc/pull/5/files#diff-1b2728ddb5be3345efdd18660ee8c9e1).   Thanks again for the suggestion.

**Comment by ashokgkumar** [comment]
Thanks.  It works now.
